
version: '2.1'

services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: flickr2
    volumes:
      - .:/flickr2
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

# bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"