# Generated by Django 2.0.13 on 2019-06-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_application', to='blog.Team'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invited_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitation', to='blog.Team'),
        ),
    ]
