# Generated by Django 2.0.13 on 2019-06-24 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20190623_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sent_applications',
            field=models.ManyToManyField(related_name='sent_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
