# Generated by Django 2.0.13 on 2019-06-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190624_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='sent_invite',
            field=models.BooleanField(default=False),
        ),
    ]
