# Generated by Django 2.0.13 on 2019-06-24 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_invite_sent_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='sent_invite',
        ),
        migrations.AddField(
            model_name='invite',
            name='sent_invite',
            field=models.ManyToManyField(blank=True, null=True, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
