# Generated by Django 2.0.13 on 2019-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190627_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='owned_by', to='blog.Team'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
