# Generated by Django 2.0.13 on 2019-06-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190627_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='owned_by', to='blog.Team'),
        ),
    ]
